export const dummyMovieListData = [
	{
		adult: false,
		backdrop_path: "/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",
		genre_ids: [28, 80, 53],
		id: 385687,
		original_language: "en",
		original_title: "Fast X",
		overview:
			"Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced: A terrifying threat emerging from the shadows of the past who's fueled by blood revenge, and who is determined to shatter this family and destroy everything—and everyone—that Dom loves, forever.",
		popularity: 1890.122,
		poster_path: "/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
		release_date: "2023-05-17",
		title: "Fast X",
		video: false,
		vote_average: 7.2,
		vote_count: 4085,
	},
	{
		adult: false,
		backdrop_path: "/cHkhb5A4gQRK6zs6Pv7zorHs8Nk.jpg",
		genre_ids: [28, 53, 80],
		id: 168259,
		original_language: "en",
		original_title: "Furious 7",
		overview:
			"Deckard Shaw seeks revenge against Dominic Toretto and his family for his comatose brother.",
		popularity: 66.966,
		poster_path: "/ktofZ9Htrjiy0P6LEowsDaxd3Ri.jpg",
		release_date: "2015-04-01",
		title: "Furious 7",
		video: false,
		vote_average: 7.2,
		vote_count: 10036,
	},
	{
		adult: false,
		backdrop_path: "/eT990B07JBhgomU5nLI2WS1WLTw.jpg",
		genre_ids: [28, 80, 18],
		id: 254473,
		original_language: "en",
		original_title: "Brick Mansions",
		overview:
			"In a dystopian Detroit, grand houses that once housed the wealthy are now homes of the city's most-dangerous criminals. Surrounding the area is a giant wall to keep the rest of Detroit safe. For undercover cop Damien Collier, every day is a battle against corruption as he struggles to bring his father's killer, Tremaine, to justice. Meanwhile, Damien and an ex-con named Lino work together to save the city from a plot to destroy it.",
		popularity: 24.389,
		poster_path: "/6OopiNRk7lWP0hPsY0eYqq2kQTi.jpg",
		release_date: "2014-04-22",
		title: "Brick Mansions",
		video: false,
		vote_average: 5.9,
		vote_count: 1439,
	},
	{
		adult: false,
		backdrop_path: "/5214eZML0xstPIfV1ldkBOheZYT.jpg",
		genre_ids: [28, 53, 12, 80],
		id: 11968,
		original_language: "en",
		original_title: "Into the Blue",
		overview:
			"When they take some friends on an extreme sport adventure, the last thing Jared and Sam expect to see below the shark-infested waters is a legendary pirate ship rumored to contain millions of dollars in gold. But their good fortune is short-lived, as a ruthless gang of criminals gets word of what they have uncovered.",
		popularity: 24.829,
		poster_path: "/h5oXcjRu0EOiAxSxYuGq58897tu.jpg",
		release_date: "2005-09-30",
		title: "Into the Blue",
		video: false,
		vote_average: 5.9,
		vote_count: 1383,
	},
	{
		adult: false,
		backdrop_path: "/2MmcWazB76kabQ1livKMqIUfN80.jpg",
		genre_ids: [28, 80, 18, 53],
		id: 22907,
		original_language: "en",
		original_title: "Takers",
		overview:
			'A seasoned team of bank robbers, including Gordon Jennings, John Rahway, A.J., and brothers Jake and Jesse Attica successfully complete their latest heist and lead a life of luxury while planning their next job. When Ghost, a former member of their team, is released from prison he convinces the group to strike an armored car carrying $20 million. As the "Takers" carefully plot out their strategy and draw nearer to exacting the grand heist, a reckless police officer inches closer to apprehending the criminals.',
		popularity: 17.758,
		poster_path: "/2It3pUKN9EdG1bIzfvKJccd0gW8.jpg",
		release_date: "2010-08-26",
		title: "Takers",
		video: false,
		vote_average: 6.2,
		vote_count: 1164,
	},
	{
		adult: false,
		backdrop_path: "/9ygcE0Ekc3of7H7HNrB4gMBmOYA.jpg",
		genre_ids: [28, 12, 878],
		id: 9562,
		original_language: "en",
		original_title: "Timeline",
		overview:
			"A group of archaeological students become trapped in the past when they go there to retrieve their professor. The group must survive in 14th century France long enough to be rescued.",
		popularity: 22.564,
		poster_path: "/uOCIrFOT4U9QXML3SLlpCxGs7BV.jpg",
		release_date: "2003-11-26",
		title: "Timeline",
		video: false,
		vote_average: 5.7,
		vote_count: 973,
	},
	{
		adult: false,
		backdrop_path: "/9uOAJFzTVNtECF6v63ISKgpYUHD.jpg",
		genre_ids: [53, 28],
		id: 180948,
		original_language: "en",
		original_title: "Vehicle 19",
		overview:
			"A parolee becomes the target of a massive police manhunt after inadvertently picking up a rental car with a female whistleblower tied up in the trunk. Now, as the police attempt to silence the woman before she can testify about the city's rampant corruption, the ex-con who just regained his freedom must defend her life, and clear his own name.",
		popularity: 13.022,
		poster_path: "/vRZobS1s3ojOpLFUbFVb2k1qDQI.jpg",
		release_date: "2013-03-07",
		title: "Vehicle 19",
		video: false,
		vote_average: 5.4,
		vote_count: 476,
	},
	{
		adult: false,
		backdrop_path: "/qxLzU7VVcwwjvqTZKAn176jMojf.jpg",
		genre_ids: [18, 28, 53, 80],
		id: 10425,
		original_language: "en",
		original_title: "The Death and Life of Bobby Z",
		overview:
			"A DEA agent provides former Marine Tim Kearney with a way out of his prison sentence: impersonate Bobby Z, a recently deceased drug dealer, in a hostage switch with a crime lord. When the negotiations go awry, Kearney flees, with Z's son in tow.",
		popularity: 12.357,
		poster_path: "/sgIthxRLUBTbaetVXvXwQEmbfn2.jpg",
		release_date: "2007-07-23",
		title: "The Death and Life of Bobby Z",
		video: false,
		vote_average: 6.2,
		vote_count: 341,
	},
	{
		adult: false,
		backdrop_path: "/p5z5X3GRnaFEqgtEa7fiGhgtUkA.jpg",
		genre_ids: [28, 80, 18, 53],
		id: 7304,
		original_language: "en",
		original_title: "Running Scared",
		overview:
			"A low-ranking thug is entrusted by his boss to dispose of a gun that killed corrupt cops, but things spiral out of control when the gun ends up in wrong hands.",
		popularity: 12.573,
		poster_path: "/wVlwZbwJlI5C33STslTyVNRGjg6.jpg",
		release_date: "2006-01-06",
		title: "Running Scared",
		video: false,
		vote_average: 7,
		vote_count: 943,
	},
	{
		adult: false,
		backdrop_path: "/pt4QcQmVhi5bAyEJvk87E7W1kcQ.jpg",
		genre_ids: [28, 35],
		id: 199420,
		original_language: "en",
		original_title: "Pawn Shop Chronicles",
		overview:
			"The stories of a missing wife, a couple of meth heads and an Elvis impersonator are connected by the items found in a small town's pawn shop.",
		popularity: 14.337,
		poster_path: "/1jQUcZ2uWUe2jIxa5efNuMhdhts.jpg",
		release_date: "2013-07-12",
		title: "Pawn Shop Chronicles",
		video: false,
		vote_average: 5.7,
		vote_count: 204,
	},
	{
		adult: false,
		backdrop_path: "/3ZiM6gm2XL8qnhZCXsTjixvaH4v.jpg",
		genre_ids: [28, 80, 18, 53],
		id: 13804,
		original_language: "en",
		original_title: "Fast & Furious",
		overview:
			"When a crime brings them back to L.A., fugitive ex-con Dom Toretto reignites his feud with agent Brian O'Conner. But as they are forced to confront a shared enemy, Dom and Brian must give in to an uncertain new trust if they hope to outmaneuver him. And the two men will find the best way to get revenge: push the limits of what's possible behind the wheel.",
		popularity: 8.302,
		poster_path: "/lUtVoRukW7WNtUySwd8hWlByBds.jpg",
		release_date: "2009-04-02",
		title: "Fast & Furious",
		video: false,
		vote_average: 6.7,
		vote_count: 6744,
	},
	{
		adult: false,
		backdrop_path: "/lvSxooYCRuF3S2kHWXYTrcOtYco.jpg",
		genre_ids: [28, 53, 80],
		id: 51497,
		original_language: "en",
		original_title: "Fast Five",
		overview:
			"Former cop Brian O'Conner partners with ex-con Dom Toretto on the opposite side of the law. Since Brian and Mia Toretto broke Dom out of custody, they've blown across many borders to elude authorities. Now backed into a corner in Rio de Janeiro, they must pull one last job in order to gain their freedom.",
		popularity: 8.327,
		poster_path: "/c5rgA1EYwMmxsQdyvLkQ8LD5Qun.jpg",
		release_date: "2011-04-20",
		title: "Fast Five",
		video: false,
		vote_average: 7.3,
		vote_count: 7619,
	},
	{
		adult: false,
		backdrop_path: "/jY9ef5nqY4xIIMu3yzW3qamUCoi.jpg",
		genre_ids: [28, 80, 53],
		id: 9799,
		original_language: "en",
		original_title: "The Fast and the Furious",
		overview:
			"Dominic Toretto is a Los Angeles street racer suspected of masterminding a series of big-rig hijackings. When undercover cop Brian O'Conner infiltrates Toretto's iconoclastic crew, he falls for Toretto's sister and must choose a side: the gang or the LAPD.",
		popularity: 7.033,
		poster_path: "/gqY0ITBgT7A82poL9jv851qdnIb.jpg",
		release_date: "2001-06-22",
		title: "The Fast and the Furious",
		video: false,
		vote_average: 7,
		vote_count: 9264,
	},
	{
		adult: false,
		backdrop_path: "/z3ioibdjWZOYeXjoiabFOFOfPI3.jpg",
		genre_ids: [28, 80, 53],
		id: 584,
		original_language: "en",
		original_title: "2 Fast 2 Furious",
		overview:
			"It's a major double-cross when former police officer Brian O'Conner teams up with his ex-con buddy Roman Pearce to transport a shipment of \"dirty\" money for shady Miami-based import-export dealer Carter Verone. But the guys are actually working with undercover agent Monica Fuentes to bring Verone down.",
		popularity: 6.389,
		poster_path: "/6nDZExrDKIXvSAghsFKVFRVJuSf.jpg",
		release_date: "2003-06-05",
		title: "2 Fast 2 Furious",
		video: false,
		vote_average: 6.5,
		vote_count: 6843,
	},
	{
		adult: false,
		backdrop_path: "/mRfI3y2oAd7ejur2di09xC9niqp.jpg",
		genre_ids: [28, 53, 80],
		id: 82992,
		original_language: "en",
		original_title: "Fast & Furious 6",
		overview:
			"Hobbs has Dominic and Brian reassemble their crew to take down a team of mercenaries; Dominic unexpectedly gets sidetracked with facing his presumed deceased girlfriend, Letty.",
		popularity: 6.198,
		poster_path: "/thSmnRdrzPBBospIOJjLZBReqzo.jpg",
		release_date: "2013-05-21",
		title: "Fast & Furious 6",
		video: false,
		vote_average: 6.8,
		vote_count: 10059,
	},
	{
		adult: false,
		backdrop_path: null,
		genre_ids: [27, 28, 878],
		id: 258157,
		original_language: "en",
		original_title: "Programmed to Kill",
		overview:
			"International terrorist leader, Fatima, is critically injured when she attempts to hijack a jumbo jet and is thwarted by Eric Matthews and his anti-terrorist organization, The Retaliators. Fatima is taken to a top-secret research institute, where she is turned into a lethal cyborg and programmed to hunt down the members of her own terrorist group. In the heat of battle, her computerized brain malfunctions, and she turns her lethal vengeance on the Retaliators. Now Eric Matthews and his team must match human cunning against deadly technology.",
		popularity: 4.617,
		poster_path: "/wjqgwl9PktkzQPTPNKdHafsoVTg.jpg",
		release_date: "1987-04-05",
		title: "Programmed to Kill",
		video: false,
		vote_average: 3.4,
		vote_count: 10,
	},
	{
		adult: false,
		backdrop_path: "/enF1PHz15lI9BaPGYYKBMnEbANh.jpg",
		genre_ids: [28],
		id: 77959,
		original_language: "en",
		original_title: "The Turbo Charged Prelude for 2 Fast 2 Furious",
		overview:
			"Turbo-Charged Prelude is a 2003 short film, directed by Philip Atwell, featuring Paul Walker, reprising his role as Brian O'Conner, in a short series of sequences which bridge The Fast and The Furious with its first sequel, 2 Fast 2 Furious.",
		popularity: 1.723,
		poster_path: "/cmhFOjy47UqrOafl0oQiygcJ7oT.jpg",
		release_date: "2003-06-03",
		title: "The Turbo Charged Prelude for 2 Fast 2 Furious",
		video: false,
		vote_average: 6.3,
		vote_count: 205,
	},
];

export const dummyGenreListData = [
	{
		id: 28,
		name: "Action",
	},
	{
		id: 12,
		name: "Adventure",
	},
	{
		id: 16,
		name: "Animation",
	},
	{
		id: 35,
		name: "Comedy",
	},
	{
		id: 80,
		name: "Crime",
	},
	{
		id: 99,
		name: "Documentary",
	},
	{
		id: 18,
		name: "Drama",
	},
	{
		id: 10751,
		name: "Family",
	},
	{
		id: 14,
		name: "Fantasy",
	},
	{
		id: 36,
		name: "History",
	},
	{
		id: 27,
		name: "Horror",
	},
	{
		id: 10402,
		name: "Music",
	},
	{
		id: 9648,
		name: "Mystery",
	},
	{
		id: 10749,
		name: "Romance",
	},
	{
		id: 878,
		name: "Science Fiction",
	},
	{
		id: 10770,
		name: "TV Movie",
	},
	{
		id: 53,
		name: "Thriller",
	},
	{
		id: 10752,
		name: "War",
	},
	{
		id: 37,
		name: "Western",
	},
];

export const dummyHomeData = {
	movieList: {
		movieListData: dummyMovieListData,
	},
	genreList: {
		genreListData: dummyGenreListData,
	},
};
